### PR TITLE
Add numbers to each section in style3.css

### PR DESCRIPTION
**Pull request by dantesolis**
Finish adding numbers to each section on `style3.css`

Example.

```
  ... omitted code

  /* #27 */  <= This was added for all "sections", it ran up till #7 before
  line-height: ;
  word-spacing: ;
  letter-spacing: ;
  white-space: ;
  word-break: ; 
  word-wrap: ;
  color: ;

  /* #28 */
  font: ;
  font-family: ;
  font-size: ;
  font-size-adjust: ;
  font-stretch: ;
  font-weight: ;
  font-smoothing: ;
  osx-font-smoothing: ;
  font-variant: ;
  font-style: ;

  ... omitted code
```

### CODE REVIEW

**Comment by brandon-rhodes** [comment]
What are the section numbers for — are these official sections of the standard? Or arbitrary numbers that we will have to change every time we choose to create a new group? If the latter, names might make more sense and be likely to be more stable.

**Comment by dantesolis** [comment]
Arbitrary numbers, should I change it to `names` then?

**Comment by brandon-rhodes** [comment]
Yes! A few-word phrase atop each section will help people navigate the file more easily than number would, I suspect, and also be future-proof and not need revision if someday we add a section somewhere in the middle of two existing sections. Thanks!

**Comment by dantesolis** [comment]
Just added the keywords to `style3.css` 

```
 /* font */
  font: ;
  font-family: ;
  font-size: ;
  font-size-adjust: ;
  font-stretch: ;
  font-weight: ;
  font-smoothing: ;
  osx-font-smoothing: ;
  font-variant: ;
  font-style: ;

  /* content */
  content: ;
  quotes: ;
```

Let me know if this works and I'll do the same for `style.css`

**Comment by brandon-rhodes** [comment]
Thanks! This does make the file easier to browse.

**Pull request merged**
